version: 0.3.{build}
build_script:
- cmd: >-
    npm install -g npm

    npm install -g grunt

    npm install -g grunt-cli

    npm install

    npm version %APPVEYOR_BUILD_VERSION%

    grunt

    npm publish

    mkdir js

    mkdir js\%APPVEYOR_BUILD_VERSION%

    copy build\emitter.js js\%APPVEYOR_BUILD_VERSION%\emitter.js

    copy build\emitter.min.js js\%APPVEYOR_BUILD_VERSION%\emitter.min.js

    copy build\emitter.js js\emitter.js

    copy build\emitter.min.js js\emitter.min.js
test: off
artifacts:
- path: js/*/emitter.js
  name: emitter.js
- path: js/*/emitter.min.js
  name: emitter.min.js
- path: js/emitter.js
  name: emitter.js
- path: js/emitter.min.js
  name: emitter.min.js
deploy:
- provider: Environment
  name: Emitter S3